config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :professionals, only: [:show, :new, :create]

  root "professionals#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/independent_professional.rb
class IndependentProfessional < Professional
  validates :crmv,
    presence: true,
    numericality: { only_integer: true },
    uniqueness: true,
    length: { is: 5 }
end

app/models/legal_person.rb
class LegalPerson < Professional
  validates :cnpj, uniqueness: true, cnpj: true, presence: true

  before_save :format_cnpj

  private
  def format_cnpj
    self.cnpj = cnpj.to_s.gsub(/\D/, "")
  end
end

app/models/professional.rb
class Professional < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: true }, email: true
  validates :phone,
    numericality: { only_integer: true },
    length: { in: 10..11 },
    allow_blank: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController
  def show
    @professional = ProfessionalPresenter.new(Professional.find(params[:id]))
  end

  def new
    @professional = Professional.new
  end

  def create
    @professional = Professional.new(professional_params)
    if @professional.save
      redirect_to professional_path(@professional)
    else
      render :new
    end
  end

  private
  def professional_params
    params.require(:professional)
      .permit(:name, :email, :phone, :address, :crmv, :cnpj, :type)
      .reject{|_, v| v.blank? }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_errors_helper.rb
module FormErrorsHelper
  def format_errors(object)
    messages = []
    object.errors.messages.each do |key, errors|
      errors.each{ |e| messages << "#{ key.to_s.humanize } #{ e }" }
    end
    messages
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProfessionalManagement</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.css',
      'application',
      media: 'all',
      'data-turbolinks-track': 'reload' %>
  </head>

  <body class="background-primary">
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/professionals/new.html.erb
<div class="container content background-content registration">
  <div class="row">
    <h3>Cadastro de Profissionais</h3>

    <ul>
      <% format_errors(@professional).each do |m| %>
        <li class="message error"><%= m %></li>
      <% end %>
    </ul>

    <%= form_for @professional, url: professionals_path(@professional) do |f| %>
      <label>Nome</label>
      <%= f.text_field :name,
        name: "professional[name]",
        placeholder: "Ex. João da Silva",
        class: "u-full-width" %>

      <label>E-mail</label>
      <%= f.text_field :email,
        name: "professional[email]",
        placeholder: "Ex. joao@gmail.com",
        class: "u-full-width" %>

      <label>Telefone</label>
      <%= f.text_field :phone,
        name: "professional[phone]",
        placeholder: "Ex. 0000000000",
        class: "u-full-width" %>

      <label>Endereço</label>
      <%= f.text_field :address,
        name: "professional[address]",
        placeholder: "Ex. Rua 9 de julho, Vila Madalena, São Paulo - SP",
        class: "u-full-width" %>

      <label>Você é um profissional do tipo</label>
      <%= f.radio_button "type",
        "IndependentProfessional",
        name: "professional[type]",
        checked: @professional.type == "IndependentProfessional" %>
      Sou um profissional liberal
      <%= f.radio_button "type",
        "LegalPerson",
        name: "professional[type]",
        checked: @professional.type == "LegalPerson" %>
      Sou uma pessoa jurídica

      <div class="independent_professional">
        <label>CRMV</label>
        <%= f.text_field :crmv,
          name: "professional[crmv]",
          placeholder: "Ex. 12345",
          class: "u-full-width" %>
      </div>

      <div class="legal_person">
        <label>CNPJ</label>
        <%= f.text_field :cnpj,
          name: "professional[cnpj]",
          placeholder: "Ex. 78.425.986/0036-15",
          class: "u-full-width" %>
      </div>

      <div class="row">
        <%= f.submit "Cadastrar", class: "button-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/professionals/show.html.erb
<div class="container content background-content registration">
  <div class="row">
    <h3>Profissional</h3>

    <ul>
      <li>Nome: <%= @professional.name %></li>
      <li>E-mail: <%= @professional.email %></li>
      <li>Telefone: <%= @professional.phone %></li>
      <li>Endereço: <%= @professional.address %></li>
      <li>Documento: <%= @professional.document %></li>
    </ul>
  </div>
</div>